We can't combine the JUnit test results, we ran out of memory on the Jenkins slave
```
 java.lang.OutOfMemoryError: Java heap space
 Caused: java.io.IOException: Remote call on EC2 (saltstack-ci) - kitchen-amd64 (i-0a9afb2a3ab858fdb) failed
    at hudson.remoting.Channel.call(Channel.java:1004)
    at hudson.FilePath.act(FilePath.java:1194)
    at hudson.FilePath.act(FilePath.java:1183)
    at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:118)
    at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:159)
    at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:253)
    at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
    at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
    at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>